### ISSUE TITLE
App DB is not created

### ISSUE THREAD

**Issue by crazyquark** [fusionpbx/fusionpbx-apps#41]
I have 2 extra apps installed: xmpp and webrtc.
No matter how many times I run the Upgrade tool their tables v_xmpp and v_webrtc are never created.

**Comment by crazyquark** [comment]
Nevermind, I fixed it myself :)
https://github.com/fusionpbx/fusionpbx-apps/pull/43

**Comment by pwilhelm949** [comment]
same issues after updating to master FusionPBX.

I notice XMPP saving to DB also doesn't seem to work. When only enabling XMPP still no luck. I had used the Fusion PBX installer on DG.

**Comment by markjcrane** [comment]
WebRTC doesn't have its own tables. And XMPP has been updated to only work with master branch. Will work again after next release.
